#!/usr/bin/env bash
set -euo pipefail

# Foolproof ETH-chain deploy helper (Sepolia/Mainnet-compatible).
#
# Required env vars:
# - ETH_RPC_URL
# - DEPLOYER_PRIVATE_KEY
# - ADMIN_ADDRESS
#
# Optional env vars:
# - TOKEN_ADDRESS              # Optional, for UI helper config only
# - PAYEE_ADDRESS              # Used only for UI config helper output
# - ARBITRATOR_ADDRESS         # default: ADMIN_ADDRESS
# - SELLER_BOND_BPS            # default: 3000 (30%)
# - BILL_TTL_SECONDS           # default: 86400 (24h)
# - BATCH_MODE_ENABLED         # default: true
# - BATCH_CIRCUIT_BREAKER      # default: false
# - OUTPUT_PATH                # default: results/deploy-v01-eth.json
# - UI_CONFIG_PATH             # default: examples/v01-console-config.json
# - WRITE_UI_CONFIG            # default: 1 (write UI helper config)
# - CHAIN_LABEL                # default: eth-like
#
# Usage:
#   ETH_RPC_URL=... DEPLOYER_PRIVATE_KEY=... ADMIN_ADDRESS=... \
#   TOKEN_ADDRESS=... PAYEE_ADDRESS=... \
#   ./scripts/deploy-v01-eth.sh

if [[ -z "${ETH_RPC_URL:-}" || -z "${DEPLOYER_PRIVATE_KEY:-}" || -z "${ADMIN_ADDRESS:-}" ]]; then
  echo "Missing required env vars: ETH_RPC_URL / DEPLOYER_PRIVATE_KEY / ADMIN_ADDRESS"
  exit 1
fi

OUTPUT_PATH="${OUTPUT_PATH:-results/deploy-v01-eth.json}"
UI_CONFIG_PATH="${UI_CONFIG_PATH:-examples/v01-console-config.json}"
WRITE_UI_CONFIG="${WRITE_UI_CONFIG:-1}"
CHAIN_LABEL="${CHAIN_LABEL:-eth-like}"
ARBITRATOR_ADDRESS="${ARBITRATOR_ADDRESS:-$ADMIN_ADDRESS}"
SELLER_BOND_BPS="${SELLER_BOND_BPS:-3000}"
BILL_TTL_SECONDS="${BILL_TTL_SECONDS:-86400}"
BATCH_MODE_ENABLED="${BATCH_MODE_ENABLED:-true}"
BATCH_CIRCUIT_BREAKER="${BATCH_CIRCUIT_BREAKER:-false}"

non_custodial_address=""
non_custodial_deploy_tx_hash=""
batch_mode_tx_hash=""
batch_breaker_tx_hash=""
echo "Deploying NonCustodialAgentPayment to ${CHAIN_LABEL} (sellerBond=${SELLER_BOND_BPS}bps, ttl=${BILL_TTL_SECONDS}s)..."
nc_output="$(
  forge create contracts/core/NonCustodialAgentPayment.sol:NonCustodialAgentPayment \
    --rpc-url "$ETH_RPC_URL" \
    --private-key "$DEPLOYER_PRIVATE_KEY" \
    --constructor-args "$ARBITRATOR_ADDRESS" "$SELLER_BOND_BPS" "$BILL_TTL_SECONDS" \
    --broadcast 2>&1
)"
non_custodial_address="$(printf "%s" "$nc_output" | rg "Deployed to:" | awk '{print $3}')"
non_custodial_deploy_tx_hash="$(printf "%s" "$nc_output" | rg "Transaction hash:" | awk '{print $3}')"
if [[ -z "$non_custodial_address" || -z "$non_custodial_deploy_tx_hash" ]]; then
  echo "Non-custodial deployment failed or output format changed."
  echo "$nc_output"
  exit 1
fi

echo "Configuring non-custodial batch controls..."
mode_output="$(
  cast send "$non_custodial_address" "setBatchModeEnabled(bool)" "$BATCH_MODE_ENABLED" \
    --rpc-url "$ETH_RPC_URL" \
    --private-key "$DEPLOYER_PRIVATE_KEY" 2>&1
)"
batch_mode_tx_hash="$(printf "%s" "$mode_output" | rg "transactionHash" | awk '{print $2}')"

breaker_output="$(
  cast send "$non_custodial_address" "setBatchCircuitBreakerPaused(bool)" "$BATCH_CIRCUIT_BREAKER" \
    --rpc-url "$ETH_RPC_URL" \
    --private-key "$DEPLOYER_PRIVATE_KEY" 2>&1
)"
batch_breaker_tx_hash="$(printf "%s" "$breaker_output" | rg "transactionHash" | awk '{print $2}')"

mkdir -p "$(dirname "$OUTPUT_PATH")"
cat > "$OUTPUT_PATH" <<EOF
{
  "chainLabel": "${CHAIN_LABEL}",
  "engineAddress": "",
  "adminAddress": "${ADMIN_ADDRESS}",
  "tokenAddress": "${TOKEN_ADDRESS:-}",
  "deployTxHash": "${non_custodial_deploy_tx_hash}",
  "allowlistTxHash": "",
  "nonCustodialAddress": "${non_custodial_address}",
  "nonCustodialDeployTxHash": "${non_custodial_deploy_tx_hash}",
  "batchModeConfigTxHash": "${batch_mode_tx_hash}",
  "batchCircuitBreakerConfigTxHash": "${batch_breaker_tx_hash}",
  "arbitratorAddress": "${ARBITRATOR_ADDRESS}",
  "sellerBondBps": "${SELLER_BOND_BPS}",
  "billTtlSeconds": "${BILL_TTL_SECONDS}",
  "batchModeEnabled": "${BATCH_MODE_ENABLED}",
  "batchCircuitBreakerPaused": "${BATCH_CIRCUIT_BREAKER}",
  "generatedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF

if [[ "$WRITE_UI_CONFIG" == "1" ]]; then
  mkdir -p "$(dirname "$UI_CONFIG_PATH")"
  cat > "$UI_CONFIG_PATH" <<EOF
{
  "engineAddress": "",
  "nonCustodialAddress": "${non_custodial_address}",
  "arbitratorAddress": "${ARBITRATOR_ADDRESS}",
  "sellerBondBps": "${SELLER_BOND_BPS}",
  "billTtlSeconds": "${BILL_TTL_SECONDS}",
  "batchModeEnabled": "${BATCH_MODE_ENABLED}",
  "batchCircuitBreakerPaused": "${BATCH_CIRCUIT_BREAKER}",
  "tokenAddress": "${TOKEN_ADDRESS:-}",
  "payeeAddress": "${PAYEE_ADDRESS:-}",
  "notes": "Auto-generated by scripts/deploy-v01-eth.sh. Fill missing values before using the console."
}
EOF
fi

echo
echo "Done."
echo "NON_CUSTODIAL_ADDRESS=${non_custodial_address}"
echo "NON_CUSTODIAL_DEPLOY_TX=${non_custodial_deploy_tx_hash}"
[[ -n "$batch_mode_tx_hash" ]] && echo "BATCH_MODE_CONFIG_TX=${batch_mode_tx_hash}"
[[ -n "$batch_breaker_tx_hash" ]] && echo "BATCH_BREAKER_CONFIG_TX=${batch_breaker_tx_hash}"
echo "Artifact written to: ${OUTPUT_PATH}"
if [[ "$WRITE_UI_CONFIG" == "1" ]]; then
  echo "UI helper config: ${UI_CONFIG_PATH}"
fi
echo
echo "Next:"
echo "1) Start UI: python3 -m http.server 8787"
echo "2) Open: http://localhost:8787/examples/v01-metamask-settlement.html"
echo "3) Paste Non-custodial/Token/Payee -> Connect -> Health -> Batch controls/Submit as needed"
