#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR_DEFAULT="${ROOT_DIR}/results/private-repo-sync"

output_dir="${OUTPUT_DIR_DEFAULT}"
private_repo_url=""
dry_run=0

usage() {
  cat <<'EOF'
Usage:
  ./scripts/private-repo-sync.sh [--private-repo-url <git-url>] [--output-dir <dir>] [--dry-run]

Description:
  Prepares a private-repo migration package for sensitive assets that must not stay in
  this public repository. The script creates a deterministic package under results/
  with placeholders and migration guidance.

Options:
  --private-repo-url <url>  Optional private repository URL for helper output.
  --output-dir <dir>        Output directory (default: results/private-repo-sync).
  --dry-run                 Print what would be generated without writing files.
  -h, --help                Show this message.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --private-repo-url)
      if [[ $# -lt 2 ]]; then
        echo "ERR  Missing value for --private-repo-url" >&2
        exit 1
      fi
      private_repo_url="$2"
      shift 2
      ;;
    --output-dir)
      if [[ $# -lt 2 ]]; then
        echo "ERR  Missing value for --output-dir" >&2
        exit 1
      fi
      output_dir="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERR  Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
manifest_path="${output_dir}/manifest.txt"
readme_path="${output_dir}/README.md"
bootstrap_script="${output_dir}/bootstrap-private-repo.sh"
karma2_template_dir="${output_dir}/karma2-template"

if [[ "${dry_run}" -eq 1 ]]; then
  echo "DRY-RUN only. Would generate:"
  echo "  - ${manifest_path}"
  echo "  - ${readme_path}"
  echo "  - ${bootstrap_script}"
  echo "  - ${karma2_template_dir}/ (copied from split-release/templates/karma2)"
  exit 0
fi

mkdir -p "${output_dir}"

cat > "${manifest_path}" <<EOF
# Private Repo Migration Manifest
generated_at_utc=${timestamp}
source_repo_public=$(git config --get remote.origin.url || echo unknown)
private_repo_url=${private_repo_url:-<set-private-repo-url>}

# Recommended private repository structure
docs/private/
scripts/private/
examples/private/
outreach/
ops-alerting/
EOF

cat > "${readme_path}" <<'EOF'
# Private Repo Migration Package

This directory is generated by `scripts/private-repo-sync.sh`.

## Goal
Move sensitive materials out of the public repository into a private repository.

## Suggested private directories
- `docs/private/` (investor, strategy, audit appendices, tokenomics parameters)
- `scripts/private/` (internal operations and partner integration scripts)
- `examples/private/` (internal demos and attack/recovery simulations)
- `outreach/` (commercial leads and partner records)
- `ops-alerting/` (owner monitoring, incident playbooks, paging integrations)

## Next steps
1. Create a private repository (example: `karma-internal`).
2. Copy this package into that private repository.
3. Populate each directory with internal assets from secure storage.
4. Configure CI and secret manager in the private repo only.
EOF

cat > "${bootstrap_script}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

mkdir -p docs/private scripts/private examples/private outreach ops-alerting
touch docs/private/.gitkeep scripts/private/.gitkeep examples/private/.gitkeep outreach/.gitkeep ops-alerting/.gitkeep

echo "Private repository skeleton prepared."
echo "Now add internal assets from secure storage."
EOF

chmod +x "${bootstrap_script}"

mkdir -p "${karma2_template_dir}"
cp -R "${ROOT_DIR}/split-release/templates/karma2/." "${karma2_template_dir}/"

echo "OK   Generated private migration package at: ${output_dir}"
